README.md, README_en.md
=> 标识GPT版本 #6

README.md, README_en.md
=> feat: add `https://chat8.io` from #15

README.md, README_en.md
=> feat: add `https://ai.cheapy.top` from #17

README.md, README_en.md
=> feat: add url from #19 #20

.github/workflows/convert_to_json.yml, README.md, README_en.md
=> feat: remove url from #22

README.md, README_en.md
=> feat: add `https://greengpt.app` from #24

README.md, README_en.md
=> feat: add url `https://chat.gpt.bz` from #29

README.md, README_en.md
=> feat: remove url from #30

README.md, README_en.md
=> update from #41 #42

README.md, README_en.md
=> Update: `https://www.tdchat.com` -> `http://www.tdchat.vip` #45

README.md
=> google bard已经可以使用

README.md, README_en.md
=> Update: #56

README.md, README_en.md
close #61 
close #62 
close #63 
close #64
=> Update: #61 #62 #63 #64

README.md, README_en.md
close #67 
close #77 
close #78
=> Add: #67 #77 #78

README.md, README_en.md
close #82 
close #83 
close #87
=> Update: #82 #83 #87

README.md, README_en.md
=> Add: #92 #93

README.md, README_en.md
=> Update: #96

README.md, README_en.md
close #98 
close #99
close #100
close #101
close #102
=> Add: #98 #99 #100 #101 #102

README.md, README_en.md
=> Update: #105

README.md, README_en.md
=> Update: #116

README.md, README_en.md
close #134
close #135 
close #136
=> Add: #134 #135 #136

README.md, README_en.md
close #140 
close #141 
close #144
=> Add: #140 #141 #144

README.md, README_en.md
close #150 
close #151 
close #152
=> Add: #150 #151 #152

README.md, README_en.md
=> Add: #154 #155

README.md, README_en.md
close #164
close #165 
close #166
close #167
=> Add: #164 #165 #166 #167

README.md, README_en.md
=> Add: #170 #173

README.md, README_en.md
=> Add: #178 #179

README.md, README_en.md
close #189 
close #190 
close #191
=> Add: #189 #190 #191

README.md, README_en.md
=> ✨ add #194

README.md
=> ✨ add #195

README.md
=> :sparkles: add #196

README.md
=> :sparkles: add #203

README.md
=> :sparkles: add #204

README.md
=> :sparkles: add #205

README.md
=> :sparkles: add #226

README.md
=> :sparkles: add #237

README.md
=> :sparkles: add #239

README.md
=> ✨  add #243, update #244

README.md
=> :sparkles: add #250

README.md
=> :sparkles: add #271

README.md
=> :sparkles: add #274

README.md
=> :sparkles: add #275

README.md
=> :sparkles: add #277

README.md
=> :sparkles: add #279

README.md
=> :sparkles: add #285

README.md
=> :sparkles: add #252

README.md
close #342 
close #344 
close #345
=> ✨ update #342 #344 #345

README.md
=> ✨ add #375 #376

README.md
=> ✨ add #377 #378

README.md, README_en.md
=> :sparkles: add #385

README.md
=> ✨ add #408

README.md
=> ✨ update #442 #443

README.md
=> ✨ add #467

README_en.md
New ChatGPT(GPT-3): https://chat.aigc101.net/
=> Added new ChatGPT

README.md
=> ✨ add #511

README.md
=> ✨ add #512 #513

README.md
=> ✨ add #514 #518

README.md
close #522 
close #523 
close #524 
close #525 
close #526
=> ✨ add #522 #523 #524 #525 #526

README.md
close #627
close #628 
close #631
close #638
=> ✨ add #627 #628 #631 #638

README.md
close #763
close #764
close #765
close #768
=> ✨ add #763 #764 #765 #768
